/*====================================================
        CODING QUEST
        COMPONENT ENGINE
====================================================*/

const QUEST_HEADER_STYLE=`<style id="questHeaderStyle">
.questHeader{position:sticky;top:0;z-index:10000;width:100%;min-height:64px;padding:8px 18px;display:flex;align-items:center;justify-content:space-between;gap:18px;background:rgba(12,18,34,.94);backdrop-filter:blur(16px);border-bottom:1px solid rgba(255,255,255,.14);box-shadow:0 8px 25px rgba(0,0,0,.28)}
.questHeaderBrand{display:flex;align-items:center;gap:9px;white-space:nowrap;flex-shrink:0}.questHeaderLogo{width:82px;height:54px;display:flex;align-items:center;justify-content:center;flex:0 0 82px}.questHeaderLogo img{width:100%;height:100%;object-fit:contain;display:block;filter:drop-shadow(0 3px 9px rgba(0,0,0,.35));transition:transform .2s ease}.questHeaderLogo img:hover{transform:scale(1.04)}.questHeaderTitle{display:block;font-weight:800;font-size:18px;letter-spacing:.8px;color:#ffd54f;text-shadow:0 0 12px rgba(255,213,79,.25)}
.questHeaderStats{display:flex;align-items:center;justify-content:flex-end;gap:14px;flex-wrap:nowrap;font-size:13px;color:#edf4ff;min-width:0}.questHeaderStats>span{white-space:nowrap}.headerProgress{display:flex;align-items:center;gap:6px}.headerProgressTrack{width:72px;height:7px;overflow:hidden;border-radius:10px;background:rgba(255,255,255,.16);display:inline-block}.headerProgressTrack i{display:block;height:100%;width:0;border-radius:10px;background:linear-gradient(90deg,#00e5ff,#7b61ff);transition:width .5s ease}.headerMissionButton,.audioBirdButton{border:1px solid rgba(255,255,255,.2);background:rgba(255,255,255,.08);color:#fff;cursor:pointer}.headerMissionButton{width:38px;height:38px;border-radius:50%;font-size:18px;transition:.2s}.headerMissionButton:hover{transform:scale(1.08)}.headerAudio{position:relative;display:flex;align-items:center}.audioBirdButton{width:42px;height:42px;border-radius:50%;font-size:22px;box-shadow:0 5px 16px rgba(0,0,0,.3);transition:transform .2s,box-shadow .2s}.audioBirdButton:hover{transform:scale(1.08);box-shadow:0 7px 20px rgba(0,0,0,.4)}.audioBirdPanel{position:absolute;right:0;top:50px;width:230px;padding:14px;border-radius:17px;background:rgba(15,23,42,.98);border:1px solid rgba(255,255,255,.16);box-shadow:0 14px 35px rgba(0,0,0,.45);color:#fff;display:none}.audioBirdPanel.open{display:block;animation:audioPanelIn .18s ease-out}.audioBirdPanel label{display:block;font-size:13px;margin-bottom:8px}.audioBirdRow{display:flex;align-items:center;gap:9px}.audioBirdRow button{border:0;background:transparent;color:#fff;font-size:20px;cursor:pointer}.audioBirdRow input{width:100%;cursor:pointer}
.spellForgeIcon{font-family:"Segoe UI Emoji","Apple Color Emoji","Noto Color Emoji","Segoe UI Symbol",sans-serif;font-style:normal;font-weight:400;line-height:1}
@keyframes audioPanelIn{from{opacity:0;transform:translateY(-5px) scale(.97)}to{opacity:1;transform:none}}
@media(max-width:850px){.questHeader{padding:7px 10px;gap:8px}.questHeaderTitle{font-size:15px;letter-spacing:.4px}.questHeaderStats{gap:8px;font-size:12px}.headerProgressTrack{width:48px}}
@media(max-width:600px){.questHeader{min-height:58px;gap:6px}.questHeaderBrand{gap:5px}.questHeaderLogo{width:54px;height:43px;flex-basis:54px}.questHeaderTitle{font-size:13px;letter-spacing:.2px}.questHeaderStats{flex:1;width:auto;justify-content:flex-end;gap:5px}.questHeaderStats>span:nth-child(4){display:none}.headerProgress{display:none}.headerMissionButton{width:35px;height:35px}.audioBirdButton{width:38px;height:38px}.audioBirdPanel{top:46px;width:210px}}
</style>`;

function QuestHeaderComponent(){return `${QUEST_HEADER_STYLE}<div class="questHeader" id="questHeader"><div class="questHeaderBrand"><a class="questHeaderLogo" href="../dashboard.html" aria-label="Coding Quest dashboard"><img src="../assets/coding-quest-logo.svg" alt="Coding Quest"></a><span class="questHeaderTitle">Coding Quest</span></div><div class="questHeaderStats"><span>⭐ <b id="headerXP">0</b></span><span>🪙 <b id="headerCoins">0</b></span><span>🏆 <b id="headerBadges">0</b></span><span>📚 <b id="headerKingdoms">0/15</b></span><span class="headerProgress"><span>📊</span><span class="headerProgressTrack"><i id="headerProgressBar"></i></span><b id="headerProgressText">0%</b></span><button class="headerMissionButton" id="headerMissionButton" type="button" onclick="showDailyMissionPopup()">🎯</button><div class="headerAudio"><div class="audioBirdPanel" id="audioBirdPanel"><label>🎵 Magic Music</label><div class="audioBirdRow"><button id="audioMuteButton" type="button" onclick="AudioManager.toggle()">🔊</button><input id="audioVolumeSlider" type="range" min="0" max="1" step="0.01" value="0.35" aria-label="Music volume" oninput="AudioManager.setVolume(this.value)"></div></div><button class="audioBirdButton" id="audioBirdButton" type="button" aria-label="Play or mute music" onclick="AudioManager.userStart();toggleAudioBirdPanel(event)">🐦</button></div></div></div>`;}

function updateQuestHeader(){const player=typeof getPlayer==="function"?getPlayer():typeof loadPlayer==="function"?loadPlayer():{};const xp=Number(player.xp)||0;const coins=Number(player.coins)||0;const badges=Array.isArray(player.badges)?player.badges.length:Number(player.badges)||0;const progress=player.progress||{};let completed=Object.values(progress).filter(v=>v===true||v?.completed===true||v?.master===true).length;if(Array.isArray(player.completedKingdoms))completed=Math.max(completed,player.completedKingdoms.length);const pct=Math.min(100,Math.round((completed/15)*100));const x=document.getElementById("headerXP"),c=document.getElementById("headerCoins"),b=document.getElementById("headerBadges"),k=document.getElementById("headerKingdoms"),p=document.getElementById("headerProgressBar"),t=document.getElementById("headerProgressText");if(x)x.textContent=xp;if(c)c.textContent=coins;if(b)b.textContent=badges;if(k)k.textContent=`${completed}/15`;if(p)p.style.width=`${pct}%`;if(t)t.textContent=`${pct}%`;}

function HeroComponent(data){return `<header class="heroSection"><div class="heroOverlay"><h1>${data.title}</h1><h2>${data.subtitle}</h2><p>${data.description}</p><button id="beginAdventure">✨ Begin Adventure</button></div></header>`;}

function NavigationComponent(data){return `<section id="kingdomMap" class="kingdomNavigation"><h2>🗺 Journey Through ${data.shortTitle}</h2><div class="magicGrid">${data.sections.map(section=>{const isSpellForge=/spell\s*forge/i.test(section.title||"");const tileIcon=isSpellForge?'<span class="spellForgeIcon">&#x1F9EA;</span>':(section.icon||"");const tileTitle=isSpellForge?"Spell Forge":section.title;return `<div class="magicTile" data-section="${section.id}"><div class="tileIcon">${tileIcon}</div><h3>${tileTitle}</h3><p>${section.subtitle}</p></div>`;}).join("")}</div></section>`;}

function ComicComponent(data){return `<section id="comicSection" class="lessonContent active"><h2>${data.comic.title}</h2><p>${data.comic.description}</p><div class="comicContainer"><img id="comicImage" src="${data.comic.folder}1.png" alt="Comic"></div><div class="comicControls"><button onclick="previousComic()">⬅ Previous</button><span id="pageNumber">Page 1</span><button onclick="nextComic()">Next ➡</button></div></section>`;}

function AnimationComponent(data){let videoHTML="";if(data.animation.type==="youtube"){videoHTML=`<iframe width="100%" height="500" src="${data.animation.source}" title="${data.animation.title}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`;}else{videoHTML=`<video controls playsinline preload="metadata"><source src="${data.animation.source}" type="video/mp4"></video>`;}return `<section id="animationSection" class="lessonContent"><h2>${data.animation.title}</h2><p>${data.animation.description}</p><div class="videoContainer">${videoHTML}</div></section>`;}

function NotesComponent(data){return `<section id="notesSection" class="lessonContent"><h2>${data.notes.title}</h2><p>${data.notes.description}</p><div class="notesContainer">${data.notes.cards.map(card=>`<div class="noteCard"><h3>${card.icon} ${card.title}</h3><p>${card.text}</p></div>`).join("")}</div></section>`;}

function CodingComponent(data){const isSQL=data.id==="sql";const runAction=isSQL?"window.runSQLCode()":"runPythonCode()";const resetAction=isSQL?"window.clearCode()":"clearCode()";const runLabel=isSQL?"⚡ Run Query":"⚡ Run Spell";const resetLabel=isSQL?'<span class="spellForgeIcon">🧹</span> Reset Query':'<span class="spellForgeIcon">🧹</span> Reset Spell';const codingTitle=isSQL?data.coding.title:'<span class="spellForgeIcon">&#x1F9EA;</span> Spell Forge';const codingControlStyle=`<style id="codingControlsStyle">.codingActions{display:flex;justify-content:center;align-items:center;gap:14px;margin:16px 0 22px;flex-wrap:wrap}.codingActions button{appearance:none;border:1px solid rgba(255,255,255,.22);padding:13px 26px;min-width:145px;border-radius:999px;font-family:inherit;font-size:15px;font-weight:800;letter-spacing:.2px;cursor:pointer;color:#fff;transition:transform .2s ease,box-shadow .2s ease,filter .2s ease}.codingActions button:hover{transform:translateY(-3px);filter:brightness(1.08)}.codingActions button:active{transform:translateY(0) scale(.98)}.codingActions button:focus-visible{outline:3px solid rgba(255,213,79,.55);outline-offset:3px}.runCodeButton{background:linear-gradient(135deg,#00b8ff,#6c63ff);box-shadow:0 8px 22px rgba(0,184,255,.28),0 0 18px rgba(108,99,255,.18)}.clearCodeButton{background:linear-gradient(135deg,#334155,#64748b);box-shadow:0 8px 18px rgba(0,0,0,.25)}@media(max-width:600px){.codingActions{gap:10px;margin:14px 0 20px}.codingActions button{min-width:132px;padding:12px 18px;font-size:14px}}</style>`;return `${codingControlStyle}<section id="codingSection" class="lessonContent"><h2>${codingTitle}</h2><p>${data.coding.description}</p><div class="codingContainer"><textarea id="codeEditor" spellcheck="false">${data.coding.defaultCode}</textarea><div class="codingActions"><button type="button" class="runCodeButton" onclick="${runAction}">${runLabel}</button><button type="button" class="clearCodeButton" onclick="${resetAction}">${resetLabel}</button></div><div class="codingButtons">${data.coding.challenges.map(challenge=>`<button type="button" onclick="loadChallenge('${challenge.id}')">${challenge.icon} ${challenge.title}</button>`).join("")}</div><pre id="output">✨ Awaiting your spell...</pre></div></section>`;}

function QuizComponent(data){return `<section id="quizSection" class="lessonContent"><h2>${data.quiz.title}</h2><p>${data.quiz.description}</p><div class="quizContainer"><div class="quizCard"><div id="quizQuestion">Loading Question...</div><div id="quizOptions"></div><div class="quizFooter"><span id="quizProgress">Question 1</span><button id="nextQuizButton" onclick="nextQuestion()">Next ▶</button></div></div></div></section>`;}

function ChallengeComponent(data){return `<section id="challengeSection" class="lessonContent"><h2>${data.challenge.title}</h2><p>${data.challenge.description}</p><div class="challengeCard"><h3>${data.challenge.icon} ${data.challenge.heading}</h3><p>${data.challenge.story}</p><ul>${data.challenge.tasks.map(task=>`<li>${task}</li>`).join("")}</ul><button id="completeKingdom">👑 Complete Kingdom</button></div></section>`;}

function FooterComponent(data){return `<footer class="kingdomFooter"><h3>🗺️ Continue Your Adventure</h3><p>You have reached the end of <b>${data.title}</b>.</p><div class="kingdomFooterActions"><button id="dashboardKingdom" class="kingdomNavButton dashboardNavButton">🏠 Dashboard</button><button id="previousKingdom" class="kingdomNavButton previousNavButton">⬅ Previous Kingdom</button><button id="nextKingdom" class="kingdomNavButton nextNavButton">Next Kingdom ➡</button></div><div class="questSiteCredit" style="margin-top:55px;padding-top:24px;border-top:1px solid rgba(255,255,255,.14);opacity:.9"><div style="font-size:18px;font-weight:600">Coding Quest</div><div style="margin-top:6px;font-size:14px">Developed by <b>Amit Yerpude</b></div></div></footer>`;}

function AudioComponent(){return ``;}
function toggleAudioBirdPanel(event){if(event)event.stopPropagation();const panel=document.getElementById("audioBirdPanel");if(!panel)return;panel.classList.toggle("open");if(window.AudioManager&&typeof AudioManager.updateControl==="function")AudioManager.updateControl();}
document.addEventListener("click",event=>{const wrap=document.querySelector(".headerAudio");if(wrap&&!wrap.contains(event.target)){const panel=document.getElementById("audioBirdPanel");if(panel)panel.classList.remove("open");}});
function RewardPopupComponent(){return `<div id="rewardPopup" class="rewardPopup"><div class="rewardBox"><h2>🎁 Reward Unlocked</h2><p id="rewardText">+10 XP</p><button onclick="closeReward()">Continue</button></div></div>`;}
function LoadingComponent(){return `<div id="loadingScreen" class="loadingScreen"><div class="loader">✨</div><h2>Loading Kingdom...</h2></div>`;}
function ParticleComponent(){return `<div id="particleContainer"></div>`;}

function renderKingdom(data){const root=document.getElementById("kingdomContainer");if(!root)return;root.innerHTML="";try{root.innerHTML+=QuestHeaderComponent();}catch(e){console.error("QuestHeader",e);}try{root.innerHTML+=HeroComponent(data);}catch(e){console.error("Hero",e);}try{root.innerHTML+=NavigationComponent(data);}catch(e){console.error("Navigation",e);}try{root.innerHTML+=ComicComponent(data);}catch(e){console.error("Comic",e);}try{root.innerHTML+=AnimationComponent(data);}catch(e){console.error("Animation",e);}try{root.innerHTML+=NotesComponent(data);}catch(e){console.error("Notes",e);}try{if(data.id==="network"){if(typeof mountSpiderWebNetworkComponent==="function")mountSpiderWebNetworkComponent();}else if(data.coding){root.innerHTML+=CodingComponent(data);}else if(typeof NetworkSimulatorComponent==="function"){root.innerHTML+=NetworkSimulatorComponent();}}catch(e){console.error("Coding/Network",e);}try{root.innerHTML+=QuizComponent(data);}catch(e){console.error("Quiz",e);}try{if(data.challenge)root.innerHTML+=ChallengeComponent(data);}catch(e){console.error("Challenge",e);}try{root.innerHTML+=FooterComponent(data);}catch(e){console.error("Footer",e);}try{root.innerHTML+=RewardPopupComponent();}catch(e){console.error("Reward",e);}setTimeout(updateQuestHeader,50);}
console.log("components.js loaded — 15 kingdom architecture");
